server:
  port: 9092

keycloak:
  server-url: http://keycloak:8080  # Имя сервиса в Docker
  realm: individuals-realm
  client-id: individuals-api
  client-secret: your-client-secret  # Должен совпадать с Keycloak
  admin-username: admin
  admin-password: admin  # Пароль администратора Keycloak